language: java
sudo: false
script: mvn clean verify
after_failure:
  - cat MSBuild_*.failure.txt
  

services:
  - docker


before_install:
- if [ ! -z \"$DOCKER_USERNAME\" ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD || true; fi

script:
- make build-image

deploy:
- provider: script
  script: make push-image
  on:
     tags: true
     condition: ${DOCKER_USERNAME} && ${DOCKER_PASSWORD}
- provider: script
  script: make push-image
  on:
     branch: latest
     condition: ${DOCKER_USERNAME} && ${DOCKER_PASSWORD}



